### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pahakalle** [TAIProjektit/paivakotipaikat#2]
Tekemättä / jatkokehitystä.

- [x] Version 1.0.0 julkaisu.
- [ ] Dokumentointi.
- [ ] Koodin uudelleen tekeminen **angular2**:della tai **angularjs**:sällä.
- [ ] Puhelin support.
- [ ] Automatisoitu testaaminen.
- [ ] **Rest api** (Mahdollistaaa mobiili sovelluksen ja lyhentää koodia).
- [ ] Token based login api:hin. (https://github.com/mevdschee/php-api-auth).
- [ ] Gui api:hin (https://github.com/nlware/vue-crud-ui).
- [ ] Jos toinen editoi lukitse kyseinen aika.
- [ ] Real time päivitykset.
- [ ] Helppokäyttöinen ota yhteyttä osio (Korvaa sähköposti kysymykset).
- [ ] Wilma tyyppiset varoitus viestit kotinäkymään, muokkauksista ja päivityksistä.
- [ ] Paremmat Admin työkalut (Tekstin muokkaus, sähköpostin lähetys ja muokkaus, yms.).
- [ ] Paremmat ohjeet ja niiden helpompi muokkaaminen (esim. Ylläpitäjän asetuksista).
- [ ] Automatisoitu ajoitettu muistutus sähköpostiviesti varauksista käyttäjille.
- [ ] Parempi apuatarvitsevat lomake (syyn/tyypin valinta ja sen helpottaminen).

**Comment by pahakalle** [comment]
Tässä hieman tekemistä seuraavalle nakitetulle :joy:
